apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-api-green
  labels:
    app: demo-api
    slot: green

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo-api
      slot: green

  template:
    metadata:
      labels:
        app: demo-api
        slot: green

    spec:
      containers:
        - name: demo-api
          image: luciav1982/demo-api-lucia:latest

          ports:
            - name: http
              containerPort: 3000

          env:
            - name: PORT
              value: "3000"

            - name: APP_ENV
              value: "green"

            - name: APP_VERSION
              value: "1.1.0"

            - name: FORCE_ERROR
              value: "false"

          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3