name: Cliente - Publicar API en K8s

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: asanchezo-duoc/AUY1104-SharedWorkflows/.github/workflows/deploy-api.yaml@main

    with:
      image-name: demo-api-lucia
      image-tag: v1
      k3s-server-public-ip: ${{ vars.K3S_SERVER_PUBLIC_IP }}

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K3S_SSH_PRIVATE_KEY: ${{ secrets.K3S_SSH_PRIVATE_KEY }}
