name: Release por Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: luciaV1982/AUY1104-SharedWorkflows/.github/workflows/deploy-api.yaml@main
    with:
      image-name: lucia-api
      image-tag: ${{ github.ref_name }}
      k3s-server-public-ip: 54.144.216.151
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
